add is_linear() function
StarikTenger/RegularLanguageProblem pull request #6
Opened 2022-10-22 12:03 UTC by SoFa325

2022-10-22 19:01 UTC, Robby-the-paladin requested changes

2022-10-22 19:01 UTC, Robby-the-paladin commented on include/objects/Grammar.h
> +>>>>>>>>> Temporary merge branch 2
Откуда здесь builder и зачем он нужен?
P.S. код очевидно не компилиться

2022-10-22 19:01 UTC, Robby-the-paladin commented on include/objects/LinearCFGChecker.h
> +	int max_recursion_depth = 10;
Что за магическая константа?

2022-10-22 19:01 UTC, Robby-the-paladin commented on include/objects/LinearCFGChecker.h
> +	Nonterminal start_symbol = Nonterminal("S");
Стартовый нетерминал в есть в грамматике как отдельное поле

2022-10-22 19:01 UTC, Robby-the-paladin commented on src/objects/LinearCFGChecker.cpp
> +}
Эта функция только для дебага?

2022-10-23 10:27 UTC, StarikTenger commented on include/objects/LinearCFGChecker.h
> +	int max_recursion_depth = 10;
10

2022-10-23 10:31 UTC, closed without merging